### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by YatlongYuan** [YGYOOO/WeChat-Shelter#3]
网页版微信下架了，这可咋整

**Comment by YGYOOO** [comment]
https://wx2.qq.com/ 没有啊

**Comment by YatlongYuan** [comment]
可能是我账号的问题吧，多谢回复

[cid:06F0767D5D69D18A575BBBB726B08EBF]

[cid:99C8C51E75659D14D80F262E5EF6D6CB]

 原始邮件
发件人: YGY<notifications@github.com>
收件人: YGYOOO/WeChat-Shelter<WeChat-Shelter@noreply.github.com>
抄送: Elan Ywan<elanyann2017@outlook.com>; Author<author@noreply.github.com>
发送时间: 2019年10月10日(周四) 15:16
主题: Re: [YGYOOO/WeChat-Shelter] 失效 (#3)


https://wx2.qq.com/ 没有啊
