### ISSUE TITLE
目前微信不支持网页版本了

### ISSUE THREAD

**Issue by fkfgq2008** [YGYOOO/WeChat-Shelter#4]
目前微信不支持网页版本了。苦

**Comment by YGYOOO** [comment]
支持啊，https://wx.qq.com

**Comment by Yoge-Code** [comment]
登录提示不支持+1

**Comment by uohzoaix** [comment]
不支持+1

**Comment by YGYOOO** [comment]
确认是https://wx.qq.com 不支持？提示什么呢？建议先关闭该插件，排除是否为该插件导致（理论上不会有影响），依然有问题的话请检查一下是不是你们公司内网禁止了微信？如果不是的话可以给微信提bug(°ー°〃)

**Comment by Yoge-Code** [comment]
不是，是接口返回的，
![image](https://user-images.githubusercontent.com/8018232/68028048-d48df580-fcee-11e9-9e28-fd1f0da3d771.png)

**Comment by YGYOOO** [comment]
https://developers.weixin.qq.com/community/develop/doc/0008006e9b470052e1e80e91756400 ，有些账号会触发安全规则，确实用不了网页微信
